version: '3.9'
services:
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - templinkshare-network

  postgres:
    image: postgres
    container_name: templinkshare-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/postgresql/data
    networks:
      - templinkshare-network

networks:
  templinkshare-network:
    driver: bridge

volumes:
  db-data:
    driver: local

